name: common
services:
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - coffeedoor-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - coffeedoor-network

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
    networks:
      - coffeedoor-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - coffeedoor-network

  postgres-exporter:
    container_name: postgres-exporter
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
    ports:
      - 9187:9187
    networks:
      - coffeedoor-network

  rabbitmq-exporter:
    container_name: rabbitmq-exporter
    image: kbudde/rabbitmq-exporter
    environment:
      RABBITMQ_URL: "http://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:15672/"
    ports:
      - 9419:9419
    networks:
      - coffeedoor-network

  redis-exporter:
    container_name: redis-exporter
    image: oliver006/redis_exporter
    command:
      - "--redis.addr=redis://${REDIS_HOST}:${REDIS_PORT}"
    ports:
      - 9121:9121
    networks:
      - coffeedoor-network

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - 9100:9100
    networks:
      - coffeedoor-network

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3003:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus
      - postgres-exporter
      - rabbitmq-exporter
      - redis-exporter
      - node-exporter
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - coffeedoor-network

  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - ./loki.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - coffeedoor-network

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - coffeedoor-network

networks:
  coffeedoor-network:
      external: true
        
volumes:
  grafana-storage:
  rabbitmq-data:
  loki-data: